### ISSUE TITLE
Shouldn't the wallpaper go to a place for all users?

### ISSUE THREAD

**Issue by Andrew-J-Larson** [Botspot/Windows-10#1]
Like maybe putting it in /usr/share/backgrounds or /usr/share/wallpapers

**Comment by Botspot** [comment]
Working on it.

**Comment by Andrew-J-Larson** [comment]
Also, on smaller displays, the wallpaper will look weird, so maybe include other resolutions?

For example, in the latest version of Windows 10, the light background, you can find all screen resolution background images used at the "C:\Windows\Web\4K\Wallpaper\Windows" directory.

Similarly, before the update changed the dark wallpaper to the light one, the dark one would be found in the same location.

If needed I can try to grab some of the files of both versions of the wallpapers.

**Comment by Botspot** [comment]
Don't worry, I've already gotten both wallpapers, and am doing some preliminary testing in a [Vdesktop](https://github.com/Botspot/vdesktop) virtual machine.

Please explain how it "looks weird" in lower resolution screens. Also, try going into Desktop Preferences and playing with the wallpaper's layout setting. I currently have it on "fill screen with image", but if you find something that works better, please let me know.

**Comment by Andrew-J-Larson** [comment]
Well when in the default display size for the raspberry pi, the windows logo is too far to the right, like in https://user-images.githubusercontent.com/19640692/90026225-e2a07780-dc6b-11ea-88b1-0fb146a9d1d7.png

**Comment by Andrew-J-Larson** [comment]
What I suggest is detecting the resolution, and then setting the background to the most conforming resolution of the background.

**Comment by Botspot** [comment]
That would require a script running on startup, changing pcmanfm's config on every boot.
Also, the number of edge cases would be frustrating. For example, what if someone's using dual monitors of different resolution?
Like a tiny TFT and a 4k screen? How would the script know which one to select?

I'd rather not do that. But maybe I could include a variety of background sizes and let the user manually choose one.

**Comment by Andrew-J-Larson** [comment]
I see what you mean, yeah at least include the other sizes.

**Comment by Andrew-J-Larson** [comment]
Btw, did just what I said, got the originals from both the 1809 and 1903 versions of windows from that folder I mentioned.

Might want to compare and make sure you have all the resolutions: https://www.mediafire.com/file/4jr1cdceqn2tkpf/file

**Comment by Botspot** [comment]
Fixed. See commit 4572fa55b2a577a92f0e5e6bb5503488b1d33cb3.
