### ISSUE TITLE
Don't forget the newest wallpaper windows 10 has...

### ISSUE THREAD

**Issue by Andrew-J-Larson** [Botspot/Windows-10#2]
Basically a light wallpaper https://wallpaperhub.app/wallpapers/1534

**Comment by Botspot** [comment]
Yes, I was aware of that. I'm pretty sure most people prefer the darker one though, so that's what I chose by default.
Will add the newer one as an option.

**Comment by Andrew-J-Larson** [comment]
Agreed I like the darker one too, but I know people that like the newer one.

**Comment by Botspot** [comment]
See commit 4572fa55b2a577a92f0e5e6bb5503488b1d33cb3.
Wallpapers are now located in `/usr/share/rpd-wallpaper`, and I've added the light version. The dark version is still the default.
