### ISSUE TITLE
[Minor Graphical Bug] Logout and then log back in, task bar icons

### ISSUE THREAD

**Issue by Andrew-J-Larson** [Botspot/Windows-10#4]
If you logout and then log back in, you'll find the sound and internet appear, but quickly disappear. Additionally, when the sound appears, it shows and absurd sound volume.

![Annotation 2020-08-12 071411](https://user-images.githubusercontent.com/19640692/90026225-e2a07780-dc6b-11ea-88b1-0fb146a9d1d7.png)

**Comment by Botspot** [comment]
That -273 is actually a CPU temperature monitor. And yes, -273 is absurd. Are you running this in a virtual machine or something?
You say "sound and internet appear, but quickly disappear." But in your screenshot, I clearly see those. Could you post a screenshot when sound and internet are missing?

**Comment by Andrew-J-Larson** [comment]
Yes, I was running it in a VM lol, that makes a lot more sense now... might
want to add temperature symbols ya know xD

**Comment by Andrew-J-Larson** [comment]
When sound, internet, and I guess the temperature monitor too, disappear it just looks like the bar as it would be without those icons.

There is nothing clickable where they would be, and no mouse hover highlights.

**Comment by Botspot** [comment]
When they disappear, open a terminal and run `killall tint2`. See if those icons now re-appear.

**Comment by Andrew-J-Larson** [comment]
Yep, they reappear after running that.

**Comment by Botspot** [comment]
Before you ran `killall tint2`, did you see the Chromium launcher, file manager launcher, and terminal launcher? on the panel?

**Comment by Andrew-J-Larson** [comment]
Nope, those disappear

**Comment by Andrew-J-Larson** [comment]
But, when the sound/internet/temp icons disappear (from the logout and login bug), those chromium/file manager/terminal icons show up

**Comment by Andrew-J-Larson** [comment]
Maybe they are replacing each other?

**Comment by Botspot** [comment]
That's good. It means tint2 is functioning properly.

So basically, there's 2 panels running at once: lxpanel and tint2. Tint2 is your taskbar/launcher, and lxpanel is everything else.
Tint2 is set to be "always on top". Tint2 doesn't cover the whole screen, as I've set boundaries on either side. On a large monitor, tint2 leaves a lot of room between the sound icon and itself. But apparently, on a lower resolution, tint2 will cover the sound icon. To fix, go to menu -> preferences -> tint2 settings. Click Edit theme. Wait until it loads, then click the Panel tab on the right. Find "length - 77 percent", and reduce that number to whatever you like. Hit Apply to refresh tint2.
When you've set the percentage just right so that tint2 _almost_ clips the sound icon, stop. Click OK, then tell me what percentage worked for you.

BTW, what VM are you using? Looks good.

**Comment by Andrew-J-Larson** [comment]
65% seems to do a good job.

Oh and it's just me using VirtualBox on Windows 10. I'm using the x86 version of raspbian to virtualize.

**Comment by Botspot** [comment]
OK, I'm closing this issue. I may decide to set tint2's default to 65%, or instead tell the user to adjust it.

You're using Raspbian desktop for x86? I'd be interested in how well [Pi-Power-Tools](https://github.com/Botspot/Pi-Power-Tools) runs on it.

**Comment by Andrew-J-Larson** [comment]
I can try out the power tools later today when I'm off work.

**Comment by Botspot** [comment]
Any updates?

**Comment by Andrew-J-Larson** [comment]
Oh sorry I forgot about this, I guess I can check out the power tools today

**Comment by Andrew-J-Larson** [comment]
So far as I see the power tools working, but I had to reinstall the VM, because some weird bug wasn't allowing to install after I applied the Windows 10 theme

**Comment by Andrew-J-Larson** [comment]
Though, it doesn't appear that anything boots in it, given that the x86 version is obviously not arm

**Comment by Andrew-J-Larson** [comment]
Also, it doesn't appear that the imaging works, but then again I was trying to image an SD card via a usb hub + usb sd card adapter.

**Comment by Botspot** [comment]
> Though, it doesn't appear that anything boots in it, given that the x86 version is obviously not arm

No, it wouldn't boot ARMhf images in a x86 environment. Did you happen to try downloading a Raspberry Pi OS for PC img and running that?



> Also, it doesn't appear that the imaging works, but then again I was trying to image an SD card via a usb hub + usb sd card adapter.

That should have worked. I'd like you to run `/home/pi/Pi-Power-Tools/flash` in a terminal and post the error output.

**Comment by Botspot** [comment]
> That should have worked. I'd like you to run `/home/pi/Pi-Power-Tools/flash` in a terminal and post the error output.

Oh wait, silly me. Flash uses `buffer`, and ARMhf executable to maximize speed. Of course, an x86 OS won't be able to run that. Thanks for trying out PPT for me on your x86 linux system.
