### ISSUE TITLE
add search function to main menu.

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/Windows-10#6]
I don't know if it's possible with LXDE, but it would be really nice to have it.

**Comment by Botspot** [comment]
If you can find a lxde-compatible menu launcher with a search box, I'll do my best to make it work.

**Comment by Itai-Nelken** [comment]
I searched for a search bar for lxde and turns out it's impossible.

**Comment by prabbit237** [comment]
Maybe the xfce4-appfinder?

https://unix.stackexchange.com/questions/67459/lxde-customize-main-menu-add-search-box-like-in-kde-kickoff-or-windows-7-vista

**Comment by Botspot** [comment]
@prabbit237 `xfce4-appfinder` appears to be a standalone app, like Catfish, not a start-menu-style app finder panel plugin.

**Comment by Itai-Nelken** [comment]
@Botspot maybe this will work: https://github.com/phoenixbyrd/panther_launcher
remove the lxde menu and put this one instead, judging by the screenshot it will look pretty similar to the real win10 one.

**Comment by Itai-Nelken** [comment]
@Botspot I asked in the [lxde forums](https://forum.lxde.org/viewtopic.php?p=55376) and someone said that no, this isn't possible with lxde, but you can use a different menu like XFCE4's whisker.

**Comment by pi-dev500** [comment]
We can also install cinnammon with the Windows-10 theme of the cinnamon store and the new windows-list of cinnamon.

**Comment by Botspot** [comment]
> We can also install cinnammon with the Windows-10 theme of the cinnamon store and the new windows-list of cinnamon.

No thanks. Right now, Windows 10 Theme doesn't change desktop environments, it only changes themes. And that was hard enough to ensure it didn't accidentally overwrite configuration.

If Windows 10 theme used Cinnamon, it would have to deactivate LXDE and activate Cinnamon. And upon uninstalling, Windows 10 theme would have to restore everything back. That would be even more difficult.

@pi-dev500 Feel free to give it a try yourself! :)

**Comment by pi-dev500** [comment]
I have just started uploading my thème installer on a private repository. I think that will be ready in two mounth and It's not very dificult to launch ```cinnamon --replace``` at the beginning of the lxde session.

**Comment by pi-dev500** [comment]
that give that:
![Capture d’écran du 2021-03-04 08-30-16](https://user-images.githubusercontent.com/77228126/109927793-050be800-7cc5-11eb-9dd2-9df0432a8b16.png)

**Comment by pi-dev500** [comment]
My installation script is new done but only @Botspot can see It. Uninstall script is not created.

**Comment by pi-dev500** [comment]
It doesn't work very well: I don't found all configs files. And windows list doesn't works on pi. that works perfectly on a x86_64 machine if cinnamon is already configurated.
Post-close edit:
It works now perfectly.
