### ISSUE TITLE
non-default user

### ISSUE THREAD

**Issue by prabbit237** [Botspot/Windows-10#7]
This is a nice theme but...........

There are those who want to run under a different user than "pi" (or even have multiple users on the device.) The install script should use $USER and not "pi." 

Such as 
````
rm -r /home/$USER/.cache/tint2 &>/dev/null
````
instead of:
````
rm -r /home/pi/.cache/tint2 &>/dev/null
````

**Comment by Botspot** [comment]
Or better yet, use the `$HOME` variable. Good catch!
