### ISSUE TITLE
Appearance Problems

### ISSUE THREAD

**Issue by ghost** [Botspot/Windows-10#8]
@Botspot This eyecandy is very useful for making your computer look so much cooler. But, after changing my computer account name, I installed the theme. However, it didn’t load everything on the desktop. Also, when you change the appearance settings, the bottom bar of the desktop starts to glitch out in size. You can also notice that every time I change my account name, it ends up breaking Pi-Apps and making it unusable, forcing me to reinstall the OS to delete the apps and all the data. Still, you’re doing great on making these apps!

**Comment by ReallyFunnyGuyGabe** [comment]
Still, the Pi-Apps application is really great for improving my Raspberry Pi. I use it to play Minecraft, and it goes really great!

**Comment by ghost** [comment]
Never mind, I found a loophole for the wallpaper thingy. Still, I recommend that you fix the name change issue, since it corrupts many apps. Hope you’re doing great today!

**Comment by Botspot** [comment]
I'm not sure why you would close this issue if there is still a problem.

**Comment by Botspot** [comment]
Could you send me a screenshot of when the "bottom bar of the desktop starts to glitch out in size"?

**Comment by ghost** [comment]
> Could you send me a screenshot of when the "bottom bar of the desktop starts to glitch out in size"?

I’ll get it there ASAP. I have another Raspberry Pi, so I’ll just show you the glitches and stuff once I get the photo.
Better yet, I can send a video.

**Comment by ghost** [comment]
Alright, here’s how the menu bar glitches when I change the appearance.
![DE64F65B-1DB0-4C1C-AD00-D8E51611D60D](https://user-images.githubusercontent.com/72320038/107185853-2cff7880-69b1-11eb-9fef-4f7214516aa7.png)
This is what happened when I changed the position of the menu bar. Yowza, doesn’t seem good.

**Comment by Botspot** [comment]
> Alright, here’s how the menu bar glitches when I change the appearance.
> This is what happened when I changed the position of the menu bar. Yowza, doesn’t seem good.

Well then, you probably don't want to do that then. ;)  
My Windows-10 theme uses **_two_** menu bars. This is necessary to maximize the realism of the theme, because no menu bar on earth had enough features to do what I wanted.

So, if you want to change the position or height of the menu bar, you will have to change each menu bar separately.

- In this case, right-click on the Start (Windows) button -> Panel Settings to change **lxpanel**.
- Go to Menu -> Preferences -> Tint2 Settings to change the **tint2** panel.

**Comment by ghost** [comment]
Now I understand. Thanks! :)
