### ISSUE TITLE
Very Nice Login Screen

### ISSUE THREAD

**Issue by ghost** [Botspot/Windows-10#9]
There is no particular issue I am having right now. I am only here to say that I like how the login screen also has the Windows font. Compliments to you.

**Comment by Botspot** [comment]
I didn't even know my own Windows-10 theme had a login screen...

**Comment by ghost** [comment]
> I didn't even know my own Windows-10 theme had a login screen...

Congratulations! Great job on working on this! Now my OS looks great!

**Comment by Botspot** [comment]
> > I didn't even know my own Windows-10 theme had a login screen...
> 
> Congratulations! Great job on working on this! Now my OS looks great!

What does the login screen look like? As I said, I didn't know this theme had a login screen.

**Comment by ghost** [comment]
> > > I didn't even know my own Windows-10 theme had a login screen...
> > 
> > 
> > Congratulations! Great job on working on this! Now my OS looks great!
> 
> What does the login screen look like? As I said, I didn't know this theme had a login screen.

Sorry for being 2 months late. If you change the wallpaper while the Windows 10 theme is on, you get a beautiful login screen. Try it out.

**Comment by Botspot** [comment]
> > > > I didn't even know my own Windows-10 theme had a login screen...
> > > 
> > > 
> > > Congratulations! Great job on working on this! Now my OS looks great!
> > 
> > 
> > What does the login screen look like? As I said, I didn't know this theme had a login screen.
> 
> Sorry for being 2 months late. If you change the wallpaper while the Windows 10 theme is on, you get a beautiful login screen. Try it out.

Nothing happens when I mess around with the Appearance Settings. :(  
Could you send me a picture of the lock screen you see?
